# === Application Info ===
spring.application.name=Lesson2
# === JSON Output ===
spring.jackson.serialization.indent-output=true
# === Logging ===
logging.level.root=INFO             
logging.level.com.example.demo=DEBUG  
